#!/usr/bin/env python3
"""
jdoom: A simple command-line Python script to generate random 
       dates and test you on your ability to compute the 
       day-of-the-week using John Conway's Doomsday Algorithm.

Usage: 
    jdoom [options] [quiz]
    jdoom [options] explain DATE
    jdoom -h | --help
    jdoom -V | --version

Options:
    -a, --after=DATE    Show only dates after DATE 
                        [default: 1800-01-01]
    -b, --before=DATE   Show only dates before DATE 
                        [default: 2199-12-31]
    -c, --config=PATH   Take run-time options from config file
                        [default: /home/jeffs/.jdoomrc]
    -n, --num-dates=N   Number of questions in the quiz.
                        Enter 0 for unlimited. [default: 3]
    -u, --untimed       Do not show user response times
    -v, --verbose       Display verbose output

Created 2019 by fantasy author, Jefferson Smith 
https://creativityhacker.ca
"""

import os
import time
import random
import datetime
#from docopt import docopt
from docoptcfg import docoptcfg

# process command line args
args = docoptcfg(__doc__, env_prefix='JDOOM_', config_option='--config', version='jdoom version 0.0.1')
# print args

dow_names = {0:'Sun', 1:'Mon', 2:'Tue', 3:'Wed', 4:'Thu', 5:'Fri', 6:'Sat'}

date_formats = ["%b %d %Y", "%Y-%m-%d", "%m/%d/%Y", "%B %d, %Y"]

def anchor_day_for_century(somedate):
    # 1800=5, 1900=3, 2000=2 2100=0
    # so 18=5, 19=3, 20=2 and 21=0
    # reduces by modulus 4 to 0=2, 1=0, 2=5, 3=3
    anchors = {0:2, 1:0, 2:5, 3:3}
    yr = somedate.year
    cycle = yr//100 % 4
    return anchors[cycle]

def is_leap_year(somedate):
    yr = somedate.year
    if yr/400 == yr//400:
        return True
    elif yr/100 == yr//100:
        return False
    elif yr/4 == yr//4:
        return True
    return False
    
def doomsday_for_year(somedate):
    anchor = anchor_day_for_century(somedate)
    century_year = somedate.year % 100
    t1 = century_year // 12
    t2 = century_year % 12
    t3 = t2 // 4
    explain = "%d %d %d %d" % (anchor, t1, t2, t3)
    return (anchor + t1 + t2 + t3) % 7, explain

def anchor_date_for_month(somedate):
    m = somedate.month
    constant_anchors = {3:7, 4:4, 5:9, 6:6, 7:11, 8:8, 9:5, 10:10, 11:7, 12:12}
    if m in constant_anchors:
        return constant_anchors[m]
    elif is_leap_year(somedate): 
        if m == 1: return 32
        if m == 2: return 29
    else:
        if m == 1: return 31
        if m == 2: return 28

def doomsday_offset_for_day(somedate):
    anchor_day = anchor_date_for_month(somedate)
    return (somedate.day - anchor_day) % 7

def weekday_of_year_in_doomsday_format(somedate):
    # datetime uses Monday=0 but doomsday calculations use Sunday=0
    # so we need to take the weekday and increment it
    return (somedate.weekday()+1) % 7

def explain_doomsday_for_date(somedate):
    dday, year_explanation = doomsday_for_year(somedate)
    anchor = anchor_date_for_month(somedate)
    dstr = somedate.strftime("%b") + " " + str(anchor) 
    offset = doomsday_offset_for_day(somedate)
    print("  Doomsday for the year was: %s = %d" % (year_explanation, 
        dday))
    print("  Anchor date for the month is: %s" % dstr)
    print("  Given date is offset from anchor day by: %d" % offset)
    print("  So anchor date is always a Doomsday (= %d) offset by %d = %d" % (dday, offset, (offset+dday) % 7))


def run_quiz_loop(after_date, before_date, num):
    print("Enter 'q' to quit.\n")
    print("Compute the day of the week for each givendate.")
    print("Use 0 for Sunday, 1 for Monday, etc.\n")

    after = after_date.toordinal()
    before = before_date.toordinal()

    i = 0
    while num == 0 or i < num:
        i += 1
        target_date = datetime.date.fromordinal(random.randint(after, before))
        weekday =  weekday_of_year_in_doomsday_format(target_date)
        showtime = time.time()
        answer = None
        try:
            #dstr = target_date.isoformat()[:10]
            dstr = target_date.strftime( random.choice(date_formats) )
            response = input("%s: " % dstr)
            # I like to enter each of the components of the calculation,
            # followed by the final answer, so that I can see my thinking on
            # the previous line when I make a mistake. Consequently, this line
            # takes all that input and then ignores everything but the last
            # component.
            answer = response.split()[-1]
        except:
            pass
        if answer == None:
            continue
        if answer.strip()[0] in 'qQxX':
            exit()
        answer = int(answer)
        answertime = time.time()
        if answer == weekday:
            if not args['--untimed']:
                print("Correct (%0.1f sec)"%(answertime-showtime))
            else:
                print("Correct")
        else:
            if not args['--untimed']:
                print("Wrong (%0.1f sec)"%(answertime-showtime))
            else:
                print("Wrong")
            print("  The correct answer is %d" % weekday)
            explain_doomsday_for_date(target_date)
        print('')

if __name__ == "__main__":
    if args['explain']:
        target_date = datetime.datetime.strptime(args['DATE'], "%Y-%m-%d").date()
        after_date = datetime.date(1800, 1, 1).toordinal()
        weekday =  weekday_of_year_in_doomsday_format(target_date)
        print("The correct answer is %d" % weekday)
        explain_doomsday_for_date(target_date)

    if args['quiz'] or not args['explain']:
        # after_date = datetime.date(1800, 01, 01).toordinal()
        # before_date = datetime.date(2199, 12, 31).toordinal()
        after_date = datetime.datetime.strptime(args['--after'], "%Y-%m-%d").date()
        before_date = datetime.datetime.strptime(args['--before'], "%Y-%m-%d").date()
        num_dates = int(args['--num-dates'])
        run_quiz_loop(after_date, before_date, num_dates)


